### ISSUE TITLE
Different values unpickled with/without validation

### ISSUE THREAD

**Issue by orlitzky** [UweSchmidt/hxt#39]
I noticed playing around with the new version that with validation enabled, optional Int attributes are unpickled to `Just 0` rather than `Nothing` like they should be. Here's a minimal test case:

Validate.hs
```Haskell
import Text.XML.HXT.Core

pickle_int :: PU (Maybe Int)
pickle_int = xpElem "int" $
               xpAttr "val" (xpOption xpInt)

main :: IO ()
main = do
  a <- runX ( xunpickleDocument pickle_int [withValidate no] "int.xml")
  print a
  b <- runX ( xunpickleDocument pickle_int [withValidate yes] "int.xml")
  print b
```

int.xml
```
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE int PUBLIC "junk" "int.dtd">
<int val=""></int>
```

int.dtd
```
<!ELEMENT int (#PCDATA)>
<!ATTLIST int val CDATA #REQUIRED>
```

And my output:
```
$ runghc Validate.hs 
[Nothing]
[Just 0]
```

**Comment by UweSchmidt** [comment]
Catching this error was a bit tricky. In the first place, in both cases unpickling should fail
due to the empty string, which does not represent a number. The picker took 0 for the empty string.
This was easy to fix.

The difference between validation/only well formed check had the following reason.
Validation includes a kind of normalization, which led to the "correct" behavior. Without
validation the internal representation of the empty attribute value was somewhat  "optimized",
and that led to the different behavior during unpickling.

There is a new hxt-9.3.1.13.tar.gz on hackage, in which both bugs are fixed.

Thanks for reporting the bug,

  Uwe

**Comment by orlitzky** [comment]
I just tried the same thing with 9.3.1.13 and got an unexpected result. In the `Validate.hs` example, the expected output (I think) is `[Nothing]`, since the `int` element and `val` attributes are there, but the `xpOption xpInt` fails on the empty text and returns `Nothing`. With 9.3.1.13 I'm getting,

```bash
$ runghc Validate.hs 

fatal error: document unpickling failed
xpCheckEmptyContents: unprocessed XML content detected
context:    attribute "val"
contents:   
[]

fatal error: document unpickling failed
xpCheckEmptyContents: unprocessed XML content detected
context:    attribute "val"
contents:   
[]
```

I believe the `xpOption xpInt` should have processed the empty `val` attribute.

**Comment by UweSchmidt** [comment]
Maybe the error message is a bit weird, but issuing an error message is intended. The `xpInt` fails when unpickling the `val` attribute, so this attribute remains unprocessed, and unprocessed attributes
lead to this `weird` error message, issued when unpickling of the whole element is finished.

If your xml doc contains an attribute value, that usually has a string representing an `int`,
but in some cases it doesn't, you should take the xpText pickler and combine this with an xpWrap, that converts the string into an `int` or throws it away and take the default value.

**Comment by orlitzky** [comment]
But, isn't that the entire point of the `xpOption` pickler? That `xpOption xpInt` should return `Nothing` when `xpInt` fails? Contrast with what happens with an empty __element__ (which I think is how it's supposed to work).

Validate.hs

```haskell
import Text.XML.HXT.Core

pickle_int :: PU (Maybe Int)
pickle_int = xpElem "int" $ xpOption xpInt

main :: IO ()
main = do
  a <- runX ( xunpickleDocument pickle_int [withValidate no] "int.xml")
  print a
```

int.xml

```xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE int PUBLIC "junk" "int.dtd">
<int></int>
```

This gives me `[Nothing]`, because the `xpInt` fails and the `xpOption` turns it into `Nothing`. But it doesn't complain about the unprocessed empty text:

```
$ runghc Validate.hs 
[Nothing]
```

The `xpOption xpInt` somehow works differently for attributes now. Maybe I have the wrong mental model, but it seems that either the example above should fail, or the attribute one should work.

**Comment by UweSchmidt** [comment]
In your test case there is no attribute `val` and in this case the `xpAttr` fails,  `xpOption` catches this and gives a `Nothing` back. That' o.k. and all attributes are processed (because there ain't any attributes) so everything is o.k.

But with an attribute `val=""` there is an attribute, and that one is not correctly processed, because
`xpInt` fails. That's the reason for the `weird` error message.

If you want to consume that attribute and ignore its value, in case of a broken value, please use the solution with the xpWrap, which checks the usability of the attribute value and throws it away if it's useless.

**Comment by orlitzky** [comment]
In the last test case I posted I'm not trying to parse an attribute at all -- I'm trying to parse the __contents__ of an empty element using `xpInt`. That fails because there are no contents, but `xpOption` catches that and gives me `Nothing` back. My belief is that parsing an empty attribute with `xpOption xpInt` should work the same as parsing an empty element with `xpOption xpInt`.

Sorry to keep bugging you, but I really think this is an unintended regression =)

**Comment by orlitzky** [comment]
NB: The test case at https://github.com/UweSchmidt/hxt/tree/master/hxt/test/unpicke-valid is failing with the same error.
